services:
  avocent-kvm:
    build: .
    image: avocent-kvm:latest
    container_name: avocent-kvm
    ports:
      - "8080:3000"
    environment:
      - DISABLE_IPV6=true
      - LC_ALL=en_US.UTF-8
      - KASM_SVC_AUDIO=0
      - KASM_SVC_AUDIO_INPUT=0
      - KASM_SVC_UPLOADS=0
      - KASM_SVC_GAMEPAD=0
      # Basic auth & page cosmetics (baseimage variables)
      - CUSTOM_USER=admin
      - PASSWORD=secure123
      - TITLE=KVM-9111
      # Variables consumed by the start-avocent.sh wrapper
      - KVM_HOSTNAME=10.0.9.111
      - KVM_USERNAME=Admin
      - KVM_PASSWORD=
      - KVM_TITLE=Avocent KVM
    restart: unless-stopped
    shm_size: 1g                # KasmVNC recommendation
    tmpfs:
      - /config:rw,size=128m
    volumes:
      - ./config.json:/usr/share/nginx/html/kasmvnc/config.json:ro